[package]
name = "octal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
phf = { version = "0.11.1", features = ["macros"] }


# for profiling
# [profile.release]
# debug = true
